-- MySQL Script generated by MySQL Workbench
-- Sat May 20 18:09:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base_libros
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema deer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `deer` ;

-- -----------------------------------------------------
-- Schema deer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deer` DEFAULT CHARACTER SET utf8mb4 ;
USE `deer` ;

-- -----------------------------------------------------
-- Table `deer`.`tipos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`tipos_usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`carreras` (
  `idCarreras` INT(11) NOT NULL AUTO_INCREMENT,
  `car_nombre` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCarreras`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`ciudades` (
  `idCiudades` INT(11) NOT NULL AUTO_INCREMENT,
  `ciu_nombre_cuidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCiudades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`alumnos` (
  `idalumnos` INT(11) NOT NULL AUTO_INCREMENT,
  `ciu_idCiudades` INT(11) NOT NULL,
  `car_idCarreras` INT(11) NOT NULL,
  `Tipos_Usuarios_idUsuarios` INT(11) NOT NULL,
  `alu_nombre` VARCHAR(45) NOT NULL,
  `alu_apellido` VARCHAR(45) NOT NULL,
  `alu_cedula` VARCHAR(45) NOT NULL,
  `alu_email` VARCHAR(45) NOT NULL,
  `alu_celular` INT(13) NOT NULL,
  PRIMARY KEY (`idalumnos`),
  CONSTRAINT `fk_alumnos_Tipos_Usuarios1`
    FOREIGN KEY (`Tipos_Usuarios_idUsuarios`)
    REFERENCES `deer`.`tipos_usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_carreras1`
    FOREIGN KEY (`car_idCarreras`)
    REFERENCES `deer`.`carreras` (`idCarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_ciudades1`
    FOREIGN KEY (`ciu_idCiudades`)
    REFERENCES `deer`.`ciudades` (`idCiudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_alumnos_ciudades1` ON `deer`.`alumnos` (`ciu_idCiudades` ) ;

CREATE INDEX `fk_alumnos_carreras1` ON `deer`.`alumnos` (`car_idCarreras` ) ;

CREATE INDEX `fk_alumnos_Tipos_Usuarios1` ON `deer`.`alumnos` (`Tipos_Usuarios_idUsuarios` ) ;


-- -----------------------------------------------------
-- Table `deer`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`pais` (
  `idPais` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`autor` (
  `idAutor` INT(11) NOT NULL AUTO_INCREMENT,
  `pais_idPais` INT(11) NOT NULL,
  `aut_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`),
  CONSTRAINT `fk_autor_pais1`
    FOREIGN KEY (`pais_idPais`)
    REFERENCES `deer`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_autor_pais1` ON `deer`.`autor` (`pais_idPais` ) ;


-- -----------------------------------------------------
-- Table `deer`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`categorias` (
  `idCategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`restricciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`restricciones` (
  `idrestricciones` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidadmaxima` INT(11) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrestricciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`libros` (
  `idLibros` INT(11) NOT NULL AUTO_INCREMENT,
  `Categorias_idCategorias` INT(11) NOT NULL,
  `restricciones_idrestricciones` INT(11) NOT NULL,
  `lib_descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `lib_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibros`),
  CONSTRAINT `fk_libros_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `deer`.`categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_restricciones1`
    FOREIGN KEY (`restricciones_idrestricciones`)
    REFERENCES `deer`.`restricciones` (`idrestricciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_libros_Categorias1` ON `deer`.`libros` (`Categorias_idCategorias` ) ;

CREATE INDEX `fk_libros_restricciones1` ON `deer`.`libros` (`restricciones_idrestricciones` ) ;


-- -----------------------------------------------------
-- Table `deer`.`detalleautores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`detalleautores` (
  `autor_idAutor` INT(11) NOT NULL,
  `libros_idLibros` INT(11) NOT NULL,
  PRIMARY KEY (`autor_idAutor`, `libros_idLibros`),
  CONSTRAINT `fk_autor_has_libros_autor1`
    FOREIGN KEY (`autor_idAutor`)
    REFERENCES `deer`.`autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_libros_libros1`
    FOREIGN KEY (`libros_idLibros`)
    REFERENCES `deer`.`libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_autor_has_libros_libros1` ON `deer`.`detalleautores` (`libros_idLibros` ) ;


-- -----------------------------------------------------
-- Table `deer`.`tiempo_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`tiempo_reserva` (
  `idTiempo_reserva` INT(11) NOT NULL AUTO_INCREMENT,
  `tiemp_reserv_fecha` DATE NOT NULL,
  PRIMARY KEY (`idTiempo_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `fun_nombre` VARCHAR(45) NOT NULL,
  `fun_apellido` VARCHAR(45) NOT NULL,
  `fun_cedula` VARCHAR(45) NOT NULL,
  `fun_email` VARCHAR(100) NOT NULL,
  `fun_telefono` INT(11) NULL,
  `ciu_idCiudades` INT(11) NOT NULL,
  PRIMARY KEY (`idFuncionario`, `ciu_idCiudades`),
  CONSTRAINT `fk_funcionario_ciudades1`
    FOREIGN KEY (`ciu_idCiudades`)
    REFERENCES `deer`.`ciudades` (`idCiudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_funcionario_ciudades1_idx` ON `deer`.`funcionario` (`ciu_idCiudades` ) ;


-- -----------------------------------------------------
-- Table `deer`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`solicitudes` (
  `idSolicitudes` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipos_Usuarios_idUsuarios` INT(11) NOT NULL,
  `Tiempo_reserva_idTiempo_reserva` INT(11) NOT NULL,
  `fun_idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idSolicitudes`),
  CONSTRAINT `fk_solicitudes_Tiempo_reserva1`
    FOREIGN KEY (`Tiempo_reserva_idTiempo_reserva`)
    REFERENCES `deer`.`tiempo_reserva` (`idTiempo_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_Tipos_Usuarios1`
    FOREIGN KEY (`Tipos_Usuarios_idUsuarios`)
    REFERENCES `deer`.`tipos_usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_funcionario1`
    FOREIGN KEY (`fun_idFuncionario`)
    REFERENCES `deer`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_solicitudes_Tipos_Usuarios1` ON `deer`.`solicitudes` (`Tipos_Usuarios_idUsuarios` ) ;

CREATE INDEX `fk_solicitudes_Tiempo_reserva1` ON `deer`.`solicitudes` (`Tiempo_reserva_idTiempo_reserva` ) ;

CREATE INDEX `fk_solicitudes_funcionario1` ON `deer`.`solicitudes` (`fun_idFuncionario` ) ;


-- -----------------------------------------------------
-- Table `deer`.`moderador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`moderador` (
  `idAprobados` INT(11) NOT NULL AUTO_INCREMENT,
  `sol_idSolicitudes` INT(11) NOT NULL,
  `fun_idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idAprobados`),
  CONSTRAINT `fk_Aprobados_solicitudes1`
    FOREIGN KEY (`sol_idSolicitudes`)
    REFERENCES `deer`.`solicitudes` (`idSolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moderador_funcionario1`
    FOREIGN KEY (`fun_idFuncionario`)
    REFERENCES `deer`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_Aprobados_solicitudes1` ON `deer`.`moderador` (`sol_idSolicitudes` ) ;

CREATE INDEX `fk_moderador_funcionario1` ON `deer`.`moderador` (`fun_idFuncionario` ) ;


-- -----------------------------------------------------
-- Table `deer`.`devueltos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`devueltos` (
  `idDevueltos` INT(11) NOT NULL AUTO_INCREMENT,
  `apro_idAprobados` INT(11) NOT NULL,
  `libro` VARCHAR(45) NOT NULL,
  `dev_fecha` DATE NOT NULL,
  PRIMARY KEY (`idDevueltos`),
  CONSTRAINT `fk_devueltos_Aprobados1`
    FOREIGN KEY (`apro_idAprobados`)
    REFERENCES `deer`.`moderador` (`idAprobados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_devueltos_Aprobados1` ON `deer`.`devueltos` (`apro_idAprobados` ) ;


-- -----------------------------------------------------
-- Table `deer`.`detalledevolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`detalledevolucion` (
  `devueltos_idDevueltos` INT(11) NOT NULL,
  `libros_idLibros` INT(11) NOT NULL,
  PRIMARY KEY (`devueltos_idDevueltos`, `libros_idLibros`),
  CONSTRAINT `fk_devueltos_has_libros_devueltos1`
    FOREIGN KEY (`devueltos_idDevueltos`)
    REFERENCES `deer`.`devueltos` (`idDevueltos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devueltos_has_libros_libros1`
    FOREIGN KEY (`libros_idLibros`)
    REFERENCES `deer`.`libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_devueltos_has_libros_libros1` ON `deer`.`detalledevolucion` (`libros_idLibros` ) ;


-- -----------------------------------------------------
-- Table `deer`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`editorial` (
  `idEditorial` INT(11) NOT NULL AUTO_INCREMENT,
  `edi_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`detalleeditorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`detalleeditorial` (
  `editorial_idEditorial` INT(11) NOT NULL,
  `libros_idLibros` INT(11) NOT NULL,
  PRIMARY KEY (`editorial_idEditorial`, `libros_idLibros`),
  CONSTRAINT `fk_editorial_has_libros_editorial1`
    FOREIGN KEY (`editorial_idEditorial`)
    REFERENCES `deer`.`editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editorial_has_libros_libros1`
    FOREIGN KEY (`libros_idLibros`)
    REFERENCES `deer`.`libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_editorial_has_libros_libros1` ON `deer`.`detalleeditorial` (`libros_idLibros` ) ;


-- -----------------------------------------------------
-- Table `deer`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`materias` (
  `idMaterias` INT(11) NOT NULL AUTO_INCREMENT,
  `mat_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `deer`.`detallesolicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`detallesolicitud` (
  `libros_idLibros` INT(11) NOT NULL AUTO_INCREMENT,
  `solicitudes_idSolicitudes` INT(11) NOT NULL,
  `Materias_idMaterias` INT(11) NOT NULL,
  PRIMARY KEY (`libros_idLibros`, `solicitudes_idSolicitudes`),
  CONSTRAINT `fk_detallesolicitud_Materias1`
    FOREIGN KEY (`Materias_idMaterias`)
    REFERENCES `deer`.`materias` (`idMaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_solicitudes_libros1`
    FOREIGN KEY (`libros_idLibros`)
    REFERENCES `deer`.`libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_solicitudes_solicitudes1`
    FOREIGN KEY (`solicitudes_idSolicitudes`)
    REFERENCES `deer`.`solicitudes` (`idSolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_libros_has_solicitudes_solicitudes1` ON `deer`.`detallesolicitud` (`solicitudes_idSolicitudes` ) ;

CREATE INDEX `fk_detallesolicitud_Materias1` ON `deer`.`detallesolicitud` (`Materias_idMaterias` ) ;


-- -----------------------------------------------------
-- Table `deer`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`profesores` (
  `idProfesores` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipos_Usuarios_idUsuarios` INT(11) NOT NULL,
  `ciu_idCiudades` INT(11) NOT NULL,
  `prof_nombre` VARCHAR(45) NOT NULL,
  `prof_apellido` VARCHAR(45) NOT NULL,
  `prof_cedula` INT NOT NULL,
  `prof_email` VARCHAR(250) NOT NULL,
  `prof_celular` INT(11) NOT NULL,
  PRIMARY KEY (`idProfesores`),
  CONSTRAINT `fk_profesores_Tipos_Usuarios1`
    FOREIGN KEY (`Tipos_Usuarios_idUsuarios`)
    REFERENCES `deer`.`tipos_usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_ciudades1`
    FOREIGN KEY (`ciu_idCiudades`)
    REFERENCES `deer`.`ciudades` (`idCiudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_profesores_Tipos_Usuarios1` ON `deer`.`profesores` (`Tipos_Usuarios_idUsuarios` ) ;

CREATE INDEX `fk_profesores_ciudades1` ON `deer`.`profesores` (`ciu_idCiudades` ) ;


-- -----------------------------------------------------
-- Table `deer`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deer`.`rol` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `fun_idFuncionario` INT(11) NOT NULL,
  `rol_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`),
  CONSTRAINT `fk_rol_funcionario1`
    FOREIGN KEY (`fun_idFuncionario`)
    REFERENCES `deer`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_rol_funcionario1` ON `deer`.`rol` (`fun_idFuncionario` ) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
